<?php

// client --> server --> web server (apache or ngnix) --> find index.php, process php and return output
// client <-- server <-- web server (apache or ngnix) <-- find index.php


// In PHP, a web server refers to software responsible for serving web pages and content to clients upon request. PHP itself is a server-side scripting language primarily used for web development. When a PHP script is requested by a client's web browser, it is executed by the PHP interpreter installed on the web server.

// The most common web server software used with PHP is Apache, but others like Nginx are also popular. These web servers are responsible for receiving requests from clients, such as web browsers, and delivering the appropriate responses, which may include HTML content generated by PHP scripts.

// Web servers are crucial components of the web infrastructure, as they handle the communication between clients and web applications, ensuring that requested resources are delivered efficiently and securely.